version: '3.8'

services:
  web:
    image: crud_transaction_be:latest  # Ini adalah nama image yang akan dihasilkan
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    build:
      context: .
      dockerfile: Dockerfile
